
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: Complaint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=Complaint;Username=postgres;Password=12345678"
    volumes:
      - ./appsettings.json:/app/appsettings.json  # Move this here if needed
volumes:
  postgres_data:

#docker-compose.yml controls how your containers are built and run